backend:
  name: github
  branch: main
  repo: deepbass/serverless-cms-azure
  base_url:  https://cmsazuredemofunc.azurewebsites.net

media_folder: src/content/images/
public_folder: /images

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'src/content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'select', options: ['page', 'blogpost','bloglisting'] }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blogposts'
    label: 'Blog Posts'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'select', options: ['blogpost'] }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "navbar"
    label: "Navbar"
    files:
      - file: "src/data/menuItems.json"
        label: "Navbar"
        name: "navbar"
        fields:
          - label: Menu Items
            name: menuItems
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Page Link", name: "url", widget: "string" }
              - { label: "Nested Links", name: "nestedLinks", widget: list, fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Page Link", name: "url", widget: "string" }]}
